config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
                     path_names: {sign_in: 'login', sign_up: 'signup'}
  root 'barbecues#index'

  resources :barbecues, only: [ :index, :show, :new, :create ] do
    resources :items, only: [:create]
  end
  resources :users, only: [:show]

  get '/api/barbecues/:id' => 'barbecues#information'
  post '/api/barbecues/:id/join' => 'barbecues#join'
  get '/api/barbecues/:id/guests' => 'barbecues#guests'
  get '/api/barbecues/:id/items' => 'barbecues#items'
  post '/api/barbecues/:id/items' => 'items#create'
  get '/api/barbecues/:id/leave' => 'barbecues#leave'

end

app/models/barbecue.rb
class Barbecue < ActiveRecord::Base
  validates :title, presence: true
  validates :venue, presence: true
  validates :date, presence: true
  has_many :users, through: :participations
  has_many :participations
  has_many :items

  def items_user
    items_list = []
    if self.items.length > 0
      self.items.each do |item|
        items_list.push({'name': item.name, 'user': item.get_user})
      end
    end
    return items_list
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :barbecue
  belongs_to :user

  def get_user
    User.find_by(id: user_id).name
  end

end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :user
  belongs_to :barbecue
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence:true
  has_many :barbecues, through: :participations
  has_many :participations
  has_many :items

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/barbecues_controller.rb
class BarbecuesController < ApplicationController
  before_action :authenticate_user!

  def index
    @barbecues = Barbecue.order(:date)
  end

  def show
    barbecue = Barbecue.find(params[:id])
    @users = barbecue.users
  end

  def new
    @bbq = Barbecue.new
  end

  def create
    bbq_params = params.require(:barbecue).permit(:title, :venue, :date)
    @bbq = Barbecue.new(bbq_params)

    unless @bbq.save
      render(:new)
    else
      redirect_to(barbecues_path)
    end
  end

  def information
    barbecue = Barbecue.find(params[:id])
    render json: barbecue
  end

  def join
    barbecue = Barbecue.find(params[:id])
    user = User.find(current_user.id)
    if barbecue.users.find_by(id: current_user.id) == nil && barbecue.users << user
      render status: 200, json: user
    else
      render status: 404, json: {error: 'Error'}
    end
  end

  def guests
    barbecue = Barbecue.find(params[:id])
    users = barbecue.users
    render json: users
  end

  def items
    barbecue = Barbecue.find(params[:id])
    items = barbecue.items_user
    render json: items
  end

  def leave
    barbecue = Barbecue.find(params[:id])
    user = User.find(current_user.id)
    barbecue.users.delete(user)
    render status: 200, json: user
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    barbecue = Barbecue.find(params[:id])
    name = params["name"]
    item = barbecue.items.new(barbecue_id: barbecue.id, name: name, user_id: current_user.id)
    if item.save
      render status: 201, json: {'name': item.name, 'user': current_user.name}
    else
      render status: 404, json: {error: 'Error'}
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @barbecues = User.find_by(id: current_user.id).barbecues
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barbecues_helper.rb
module BarbecuesHelper
  def format_date(date)
    return date.strftime('%B, %e %Y at %l:%M %P')
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/barbecues/index.html.erb
<h1>BBQs</h1>
<a href="<%= new_barbecue_path %>" class="btn btn-primary">
  Add a new BBQ
</a>

<ul class="list-unstyled">
  <% @barbecues.each do |bbq| %>
    <li data-bbq="<%= bbq.id %>">
      <h2>
        <a href="<%= barbecue_path(bbq.id) %>">
          <%= bbq.title %>
        </a>
      </h2>

      <dl>
        <dt>Date:</dt>
        <dd><%= format_date(bbq.date) %></dd>
        <dt>Venue:</dt>
        <dd><%= bbq.venue %></dd>
      </dl>

      <button class="btn btn-success" data-hook="join-bbq">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Join <%= bbq.title %>

      </button>

    </li>

  <% end %>
</ul>

app/views/barbecues/new.html.erb
<h1>Add a new BBQ</h1>

<% if @bbq.errors.any? %>
  <ul class="list-unstyled">
    <% @bbq.errors.full_messages.each do |msg| %>
      <li class="alert alert-danger" role="alert"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @bbq do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :venue %>
    <%= form.text_field :venue, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.date_field :date, class: 'form-control' %>
  </div>

  <button type="submit" class="btn btn-success">
    Add BBQ
  </button>
<% end %>

app/views/barbecues/show.html.erb
<h1>BBQ</h1>

<div data-hook="bbq-info" data-bbq="<%= params[:id] %>"></div>

<div data-hook="bbq-item-form" data-bbq="<%= params[:id] %>">

<% if @users.find_by(id: current_user.id) %>
<h4>Add an item</h4>
<form>
  <input type='text' name='name' placeholder='name' id='new-item'>
  <button type='submit' data-bbq="<%= params[:id] %>" id='btn-new-item'>Add!</button>
</form>

</div>

<a href="<%= barbecues_path %>">Back to list of BBQs</a>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barbecues</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', defer: true %>
  <%= csrf_meta_tags %>
</head>
<body data-hook="controller-<%= controller_name %> action-<%= action_name %>">

  <%= render 'partials/header' %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/partials/_header.html.erb
<div class='header'>
  <% if current_user %>
    <%= current_user.name %>, <%= current_user.email %>
    <%= link_to('logout', destroy_user_session_path, method: :delete) %>
    <%= link_to('My profile', user_path(current_user)) %>
    <%= link_to('Index', barbecues_path) %>
  <% else %>
    <%= link_to('login', new_user_session_path) %>
    <%= link_to('signup', new_user_registration_path) %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= current_user.name %></h1>

<ul>
<% @barbecues.each do |barbecue| %>
  <li id="li-<%= barbecue.id %>"><%= barbecue.title %><a href="/" data-id="<%= barbecue.id %>" id='btn-leave'>Leave the barbecue</a></li>
<% end %>
</ul>